parameters: {}
environment:
  ENV: "production"
  MONGODB_URI: "mongodb+srv://jefstore-gasstations-user:3MnFvf9xgQXHpXSz@kms-cluster.ygdqm.mongodb.net/?retryWrites=true&w=majority&appName=kms-cluster"
  MONGODB_DATABASE: "jefstore-gasstations-database"



packages:
  - name: authentications
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: create
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
  - name: test
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
  - name: purchase_orders
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: get-one
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}


