parameters: {}
environment:
  ENV: "production"
  MONGODB_URI: "mongodb+srv://jefstore-gasstations-user:3MnFvf9xgQXHpXSz@kms-cluster.ygdqm.mongodb.net/?retryWrites=true&w=majority&appName=kms-cluster"
  MONGODB_DATABASE: "jefstore-gasstations-database"



packages:
  - name: addstocks
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: get-all
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
  - name: authentications
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: create
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
  - name: pumps
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: get-by-dispenser-name
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: get-latest-pump-inventories-by-location 
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: get-pumps-by-location
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
  - name: pump_inventories
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: get-latest-by-pump-id-and-location
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}

  - name: dispensers
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: get-by-location
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
  - name: inventories
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:

      - name: get-empty-form-item 
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: get-latest-empty-form
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: get-latest-filled-form
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: patch-empty-form-item
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
  - name: sales-invoices
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: delete-item-of-empty-form 
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: get-empty-form-employees 
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: get-latest-empty-form
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: get-latest-filled-form 
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}

      - name: patch-employee-to-empty-form
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}

      - name: post-item-to-empty-form
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: validate-current-form-qr-code
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}

  - name: test
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
